"""
API Module

This module provides the FastAPI endpoints for the Ontorum graph database.
It uses the graph_grammar module for validation of relationships.
"""

from typing import List, Optional, Dict, Any
from fastapi import FastAPI, HTTPException, Depends
from pydantic import BaseModel, field_validator
import logging
from fastapi.middleware.cors import CORSMiddleware
import json
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse, FileResponse
from fastapi.staticfiles import StaticFiles
import os

from .models import Node, Relationship
from .ontology_loader import get_ontology
from .graph_grammar import GraphLinter
from .database import OntorumDB
from .llm import LLMService
from .analysis import router as analysis_router
from .graph_statistics import GraphStatsAnalyzer, GraphStats
from .grammar_manager import (
    list_grammars,
    get_current_grammar_name,
    set_current_grammar,
    read_grammar,
    write_grammar,
    duplicate_grammar,
    delete_grammar,
)

app = FastAPI()

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5174"],  # Frontend dev server
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include the analysis router
app.include_router(analysis_router, prefix="/api/analysis")

db = OntorumDB()
logger = logging.getLogger(__name__)

def get_db():
    """Dependency to get database instance."""
    try:
        yield db
    finally:
        pass  # Connection management is handled by the OntorumDB class

# Request/Response Models
class NodeCreate(BaseModel):
    name: str
    type: str
    description: str = ""

    @field_validator('type')
    @classmethod
    def type_must_be_in_ontology(cls, v: str) -> str:
        """Validate that the type string is a known node type in the ontology."""
        if v not in get_ontology().node_types:
            raise ValueError(f"Unknown node type: '{v}'. Must be one of {list(get_ontology().node_types)}")
        return v

class NodeUpdate(BaseModel):
    name: Optional[str] = None
    description: Optional[str] = None

class NodeResponse(BaseModel):
    """Response model for nodes using Neo4j IDs."""
    id: str  # Neo4j ID
    elementId: str  # Same as id
    name: str
    type: str
    description: str = ""

class RelationshipCreate(BaseModel):
    """Schema for creating a new relationship."""
    type: str
    source: str
    target: str
    properties: Optional[dict] = None

class RelationshipResponse(BaseModel):
    """Schema for relationship responses."""
    id: str
    type: str
    source: str
    target: str
    properties: Optional[dict] = None

# LLM Request/Response Models
class LLMInstructionData(BaseModel):
    """Model for structured instruction data."""
    relationship_type: str
    source_type: str
    target_type: str
    is_source: bool
    additional_instructions: Optional[str] = None

class LLMGenerateRequest(BaseModel):
    """Request model for LLM node generation."""
    instruction: LLMInstructionData
    context: Optional[Dict[str, Any]] = None

class LLMCandidate(BaseModel):
    """Model for an LLM-generated node candidate."""
    name: str
    type: str
    description: str

class LLMGenerateResponse(BaseModel):
    """Response model for LLM node generation."""
    candidates: List[Dict[str, Any]]
    message: Optional[str] = None

class LLMEditDescriptionRequest(BaseModel):
    """Request model for editing a node's description using the LLM."""
    node_id: str
    instruction: Optional[str] = "Make this longer"

# Node Endpoints
@app.post("/api/nodes", response_model=NodeResponse)
async def create_node(node_data: NodeCreate):
    """Create a new node and return it with its Neo4j ID."""
    try:
        # node_data.type is already validated by NodeCreate Pydantic model
        # All nodes are now created as instances of the base Node model
        logger.info(f"API create_node: Received node_data: {node_data.model_dump_json(indent=2)}")
        node_instance = Node(
            name=node_data.name,
            type=node_data.type, 
            description=node_data.description or ''
            # If Node model were to have a generic `properties: Dict[str, Any]` field,
            # and NodeCreate also had it, we could pass additional properties here.
            # For now, Node only takes common fields.
        )
        logger.info(f"API create_node: Created Node instance: {{id: {node_instance.id}, type: {node_instance.type}, name: {node_instance.name}}}")
        
        # db.add_node expects an object with at least .id (generated by Node), .type, .name, .description
        created_node_from_db = db.add_node(node_instance)
        logger.info(f"API create_node: Received from db.add_node: {json.dumps(created_node_from_db, indent=2)}")
        return node_to_response(created_node_from_db)
    except HTTPException: 
        raise
    except ValueError as e: # Catch Pydantic validation errors from Node instantiation if any apart from type
        logger.error(f"Error creating node instance: {str(e)}")
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        logger.error(f"Error creating node: {str(e)}")
        if "not found in ontology" in str(e):
             raise HTTPException(status_code=400, detail=str(e))
        raise HTTPException(status_code=500, detail=f"Internal server error creating node: {str(e)}")

def node_to_response(node: dict) -> dict:
    """Convert a node from database format to API response format."""
    return {
        "id": node["id"],  # Already Neo4j ID
        "elementId": node["id"],  # Use same ID
        "name": node["name"],
        "type": node["type"].lower(),  # Ensure consistent lowercase
        "description": node.get("description", "")
    }

@app.get("/api/nodes/{node_id}", response_model=NodeResponse)
async def get_node(node_id: str):
    """Get a node by ID."""
    try:
        logger.info(f"API get_node: Requesting node_id: {node_id}")
        node = db.get_node(node_id)
        if not node:
            logger.warning(f"API get_node: Node not found for ID: {node_id}")
            raise HTTPException(status_code=404, detail="Node not found")
        logger.info(f"API get_node: Received from db.get_node for ID {node_id}: {json.dumps(node, indent=2)}")
        return node_to_response(node)
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error getting node: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

@app.put("/api/nodes/{node_id}", response_model=NodeResponse)
async def update_node(node_id: str, node_data: NodeUpdate):
    """Update a node's name and description."""
    try:
        existing = db.get_node(node_id)
        if not existing:
            raise HTTPException(status_code=404, detail="Node not found")

        updated_name = node_data.name if node_data.name is not None else existing["name"]
        updated_desc = node_data.description if node_data.description is not None else existing.get("description", "")

        updated = db.update_node(node_id, updated_name, updated_desc)
        return node_to_response(updated)
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error updating node: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/nodes/type/{node_type}", response_model=List[NodeResponse])
async def get_nodes_by_type(node_type: str):
    """Get all nodes of a specific type."""
    try:
        try:
            node_type_enum = get_ontology().NodeType(node_type)
        except ValueError:
            raise HTTPException(status_code=400, detail=f"Invalid node type: {node_type}")
        nodes = db.get_nodes_by_type(node_type_enum)
        return [node_to_response(node) for node in (nodes if nodes else [])]
    except Exception as e:
        logger.warning(f"Error getting nodes of type {node_type}: {str(e)}")
        return []

# Relationship Endpoints
@app.post("/api/relationships", response_model=RelationshipResponse)
def create_relationship(rel_data: RelationshipCreate, db: OntorumDB = Depends(get_db)):
    """Create a new relationship between nodes."""
    logger.info(f"API create_relationship: Received rel_data: {rel_data.model_dump_json(indent=2)}")
    
    source_node = db.get_node(rel_data.source)
    target_node = db.get_node(rel_data.target)
    
    logger.info(f"API create_relationship: Fetched source_node for ID {rel_data.source}: {json.dumps(source_node, indent=2) if source_node else 'Not found'}")
    logger.info(f"API create_relationship: Fetched target_node for ID {rel_data.target}: {json.dumps(target_node, indent=2) if target_node else 'Not found'}")

    if not source_node or not target_node:
        logger.error(f"API create_relationship: One or both nodes not found. Source ID: {rel_data.source}, Target ID: {rel_data.target}")
        raise HTTPException(status_code=404, detail="One or both nodes not found")

    try:
        source_type_str = source_node["type"].lower() # This is string e.g. "particular"
        target_type_str = target_node["type"].lower() # This is string e.g. "universal"
        rel_type_str = rel_data.type                 # This is string e.g. "INSTANCE_OF"
        
        # Convert rel_type_str to Enum member for GraphLinter
        try:
            rel_type_enum = get_ontology().RelationshipType(rel_type_str)
        except ValueError:
             raise HTTPException(status_code=400, detail=f"Invalid relationship type string: '{rel_type_str}'")

        is_valid, error_msg = GraphLinter.validate_relationship(
            from_type=source_type_str, # Expected as string
            to_type=target_type_str,   # Expected as string
            rel_type=rel_type_enum     # Expected as Enum member
        )
        if not is_valid:
            raise HTTPException(status_code=400, detail=error_msg)
    except HTTPException: # Re-raise specific HTTP exceptions
        raise
    except Exception as e: # Catch other potential errors during validation
        logger.error(f"Error validating relationship: {str(e)}")
        raise HTTPException(status_code=400, detail=f"Error validating relationship: {str(e)}")

    relationship_to_create = {
        'type': rel_data.type, # Use the original string for DB creation
        'source': source_node['id'],
        'target': target_node['id'],
        'properties': rel_data.properties
    }
    logger.info(f"API create_relationship: Attempting to create relationship: {json.dumps(relationship_to_create, indent=2)}")

    try:
        result = db.create_relationship(relationship_to_create)
        logger.info(f"API create_relationship: Successfully created relationship: {json.dumps(result, indent=2)}")
        return RelationshipResponse(**result)
    except Exception as e:
        logger.error(f"Error creating relationship in DB: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/api/relationships/{node_id}", response_model=List[RelationshipResponse])
def get_node_relationships(node_id: str, db: OntorumDB = Depends(get_db)):
    """Get all relationships for a node."""
    try:
        relationships = db.get_node_relationships(node_id)
        return [RelationshipResponse(**rel) for rel in relationships]
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

def _convert_relationship(rel: Relationship) -> dict:
    """Convert a relationship from database format to API response format."""
    return {
        "source": str(rel.source),
        "target": str(rel.target),
        "type": rel.type,
        "properties": rel.properties or {}
    }


# Schema Endpoints
@app.get("/api/schema/node-types")
async def get_node_types():
    """Get all available node types with their metadata."""
    types_response = []
    current_ontology = get_ontology()
    for type_key in current_ontology.node_types:
        metadata = current_ontology.node_metadata.get(type_key, {})
        types_response.append({
            "value": type_key,
            "label": metadata.get("label", type_key.capitalize()),
            "metadata": metadata
        })
    return {"types": types_response}

@app.get("/api/schema/relationship-types")
async def get_relationship_types():
    """Get all available relationship types."""
    types_response = []
    current_ontology = get_ontology()
    for rel_type_enum in current_ontology.RelationshipType:
        types_response.append({
            "value": rel_type_enum.value,
            "label": rel_type_enum.value.replace('_', ' ').capitalize()
        })
    return {"types": types_response}

@app.get("/api/schema/allowed-relationship-schemas")
async def get_allowed_relationship_schemas():
    """Get all allowed relationship combinations, including properties from the ontology spec."""
    allowed_schemas_api = []
    current_ontology = get_ontology()
    linter_schemas = GraphLinter.get_allowed_relationship_schemas()

    rules_properties_map = {rule["name"]: rule.get("properties", []) for rule in current_ontology.relationship_rules}

    for schema in linter_schemas:
        allowed_schemas_api.append({
            "from_type": schema.from_type.value,
            "to_type": schema.to_type.value,
            "relationship_type": schema.relationship_type.value,
            "properties": rules_properties_map.get(schema.relationship_type.value, [])
        })
    return {"relationships": allowed_schemas_api}

# LLM Endpoints
@app.post("/api/llm/generate", response_model=LLMGenerateResponse)
async def generate_nodes(request: LLMGenerateRequest):
    """Generate node candidates using LLM."""
    try:
        # --- Backend Guard-rail: Validate instruction against context and ontology --- 
        if request.context and request.context.get("node_type"): # Use .get() for safety
            context_node_type = request.context["node_type"]       # Use dictionary access
            instruction = request.instruction                 # instruction is a Pydantic model, attribute access is fine
            rel_type_str = instruction.relationship_type
            is_source_context = instruction.is_source

            rule = next((r for r in get_ontology().relationship_rules if r["name"] == rel_type_str), None)

            if not rule:
                raise HTTPException(status_code=400, detail=f"Invalid relationship type '{rel_type_str}' in instruction.")

            if is_source_context:
                if context_node_type not in rule["from"]:
                    raise HTTPException(
                        status_code=400, 
                        detail=f"Context node of type '{context_node_type}' cannot be the source for a '{rel_type_str}' relationship. "
                               f"Valid source types are: {rule['from']}. Instruction stated source type: '{instruction.source_type}'."
                    )
                if instruction.source_type != context_node_type:
                    raise HTTPException(
                        status_code=400,
                        detail=f"Instruction source_type '{instruction.source_type}' does not match context node type '{context_node_type}' when context is source."
                    )
            else: # Context node is TARGET
                if context_node_type not in rule["to"]:
                    raise HTTPException(
                        status_code=400, 
                        detail=f"Context node of type '{context_node_type}' cannot be the target for a '{rel_type_str}' relationship. "
                               f"Valid target types are: {rule['to']}. Instruction stated target type: '{instruction.target_type}'."
                    )
                if instruction.target_type != context_node_type:
                     raise HTTPException(
                        status_code=400,
                        detail=f"Instruction target_type '{instruction.target_type}' does not match context node type '{context_node_type}' when context is target."
                    )
        # --- End of Backend Guard-rail --- 

        logger.info("Step 3: API - Request received (passed guard-rails)", extra={
            "instruction": request.instruction.dict(),
            "context": json.dumps(request.context if request.context else {}, indent=2),
            "request_data": json.dumps(request.dict(), indent=2)
        })
        
        llm_service = LLMService()
        logger.info("Step 3: API - Calling LLM service")
        
        # request.context is already a dict or None here. Pass it directly.
        # request.instruction is a Pydantic model, .dict() is correct.
        candidates = await llm_service.generate_candidates(request.instruction.dict(), request.context)
        
        logger.info("Step 3: API - Received candidates from LLM service", extra={
            "candidates_count": len(candidates),
            "raw_candidates": json.dumps(candidates, indent=2)
        })
        
        response = LLMGenerateResponse(
            candidates=candidates,
            message="Successfully generated candidates"
        )
        
        logger.info("Step 3: API - Sending response", extra={
            "candidates_count": len(candidates),
            "candidates": json.dumps(candidates, indent=2),
            "full_response": json.dumps(response.dict(), indent=2),
            "response_model": str(type(response))
        })
        
        return response

    except ValueError as e: # Catches ValueErrors from LLMService, Pydantic model validation if any
        logger.error(f"ValueError in /api/llm/generate: {str(e)}", exc_info=True)
        raise HTTPException(status_code=400, detail=str(e))
    except HTTPException: # Re-raise HTTPExceptions explicitly raised by guard-rail or other logic
        raise
    except Exception as e: # Catch-all for unexpected errors
        logger.error(f"Unexpected error in /api/llm/generate: {str(e)}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Internal server error during candidate generation: {str(e)}")


@app.post("/api/llm/edit-description", response_model=NodeResponse)
async def llm_edit_description(request: LLMEditDescriptionRequest, db: OntorumDB = Depends(get_db)):
    """Use the LLM to edit a node's description and update it."""
    try:
        node = db.get_node(request.node_id)
        if not node:
            raise HTTPException(status_code=404, detail="Node not found")

        llm_service = LLMService()
        new_desc = await llm_service.edit_description(node, request.instruction)
        updated = db.update_node(request.node_id, node["name"], new_desc)
        return node_to_response(updated)
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error editing description with LLM: {e}")
        raise HTTPException(status_code=500, detail="Failed to edit description")

@app.delete("/api/nodes/{node_id}")
async def delete_node(node_id: str, db: OntorumDB = Depends(get_db)):
    """Delete a node and all its relationships."""
    try:
        # First check if node exists
        node = db.get_node(node_id)
        if not node:
            raise HTTPException(status_code=404, detail="Node not found")
        
        # Delete the node and its relationships
        success = db.delete_node(node_id)
        if not success:
            raise HTTPException(status_code=500, detail="Failed to delete node")
        
        return {"status": "success", "message": "Node and its relationships deleted"}
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error deleting node: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

@app.delete("/api/relationships/{relationship_id}")
async def delete_relationship(relationship_id: str, db: OntorumDB = Depends(get_db)):
    """Delete a specific relationship."""
    try:
        # Delete the relationship
        success = db.delete_relationship(relationship_id)
        if not success:
            raise HTTPException(status_code=404, detail="Relationship not found")
        
        return {"status": "success", "message": "Relationship deleted"}
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error deleting relationship: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/api/graph/statistics", response_model=GraphStats)
async def get_graph_statistics(db: OntorumDB = Depends(get_db)):
    """Return overall graph statistics for frontend display."""
    try:
        analyzer = GraphStatsAnalyzer(db)
        return analyzer.compute()
    except Exception as e:
        logger.error(f"Error computing graph statistics: {e}")
        raise HTTPException(status_code=500, detail="Failed to compute graph statistics")

@app.post("/api/database/clear")
async def clear_database_endpoint(db: OntorumDB = Depends(get_db)):
    """Remove all nodes and relationships from the database."""
    try:
        db.clear_database()
        return {"status": "success", "message": "Database cleared"}
    except Exception as e:
        logger.error(f"Error clearing database: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to clear database")


@app.get("/api/database/export")
async def export_database_endpoint(db: OntorumDB = Depends(get_db), filename: str = "ontorum_export.json"):
    """Export the database and return it as a downloadable JSON file."""
    try:
        data = db.export_to_dict()
        headers = {"Content-Disposition": f"attachment; filename={filename}"}
        return JSONResponse(content=data, headers=headers)
    except Exception as e:
        logger.error(f"Error exporting database: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to export database")


from pydantic import BaseModel


class ImportRequest(BaseModel):
    data: Dict[str, Any]
    clear: bool = False


class GrammarSelectRequest(BaseModel):
    name: str


class GrammarDuplicateRequest(BaseModel):
    name: str
    new_name: str


@app.post("/api/database/import")
async def import_database_endpoint(request: ImportRequest, db: OntorumDB = Depends(get_db)):
    """Import a database from JSON data."""
    try:
        db.load_from_dict(request.data, clear=request.clear)
        return {"status": "success"}
    except Exception as e:
        logger.error(f"Error importing database: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to import database")


# --- Grammar Management Endpoints ---
@app.get("/api/grammars")
def list_grammars_endpoint():
    return {"grammars": list_grammars(), "current": get_current_grammar_name()}


@app.post("/api/grammars/select")
def select_grammar_endpoint(req: GrammarSelectRequest):
    try:
        set_current_grammar(req.name)
        # Reload ontology with new grammar
        get_ontology()
        return {"current": get_current_grammar_name()}
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))


@app.post("/api/grammars/duplicate")
def duplicate_grammar_endpoint(req: GrammarDuplicateRequest):
    try:
        duplicate_grammar(req.name, req.new_name)
        return {"status": "success"}
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))


@app.get("/api/grammars/{name}")
def get_grammar_endpoint(name: str):
    try:
        return read_grammar(name)
    except Exception as e:
        raise HTTPException(status_code=404, detail=str(e))


@app.put("/api/grammars/{name}")
def update_grammar_endpoint(name: str, data: Dict[str, Any]):
    try:
        write_grammar(name, data)
        if get_current_grammar_name() == name:
            get_ontology()
        return {"status": "success"}
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))


@app.delete("/api/grammars/{name}")
def delete_grammar_endpoint(name: str):
    try:
        delete_grammar(name)
        return {"status": "success"}
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

# --- START Custom Exception Handlers ---
@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request, exc: RequestValidationError):
    # Log the detailed Pydantic validation errors
    logger.error(f"Pydantic RequestValidationError for URL '{request.url}':\n{exc.errors()}\nRaw request body might have been: {exc.body}", exc_info=False) # exc_info=False as exc.errors() is detailed enough
    return JSONResponse(
        status_code=422,
        content={"detail": exc.errors()},
    )

@app.exception_handler(HTTPException) # Handler for HTTPExceptions raised by our code
async def http_exception_handler(request, exc: HTTPException):
    logger.error(f"HTTPException for URL '{request.url}': Status={exc.status_code}, Detail={exc.detail}", exc_info=False)
    return JSONResponse(
        status_code=exc.status_code,
        content={"detail": exc.detail},
    )

@app.exception_handler(Exception) # General catch-all for other unexpected errors
async def general_python_exception_handler(request, exc: Exception):
    logger.error(f"Unhandled Python exception for URL '{request.url}': {type(exc).__name__} - {exc}", exc_info=True)
    return JSONResponse(
        status_code=500,
        content={"detail": "Internal server error. Please check logs."},
    )
# --- END Custom Exception Handlers ---

# Mount static files (for the frontend) - THIS MUST BE AFTER API ROUTES AND EXCEPTION HANDLERS
# IMPORTANT: The directory path will be /srv/ontorum on EC2 (set by env var)
# or an absolute path to frontend/dist locally (default).

# Get the absolute path of the directory where api.py is located
API_DIR = os.path.dirname(os.path.abspath(__file__))
# Construct the absolute path to the local static files directory (frontend/dist)
# This assumes api.py is in backend/ and frontend/ is a sibling directory.
DEFAULT_STATIC_FILES_PATH = os.path.join(API_DIR, "..", "frontend", "dist")

STATIC_FILES_PATH = os.getenv("STATIC_FILES_DIR", DEFAULT_STATIC_FILES_PATH)
logger.info(f"Resolved STATIC_FILES_PATH={STATIC_FILES_PATH}")

# Path to the index.html for the SPA
index_file_path = os.path.join(STATIC_FILES_PATH, "index.html")

# This handles local dev where `frontend/dist` might not be built,
# and also allows tests to run without requiring a frontend build.
if os.path.exists(STATIC_FILES_PATH):
    logger.info(f"Static files directory found at {STATIC_FILES_PATH}")

    # Mount specific directories for assets. Vite typically uses an 'assets' folder.
    # Adjust or add more app.mount lines if your build outputs other top-level static dirs.
    assets_path = os.path.join(STATIC_FILES_PATH, "assets")
    if os.path.exists(assets_path):
        logger.info(f"Mounting static assets from {assets_path} at /assets")
        app.mount("/assets", StaticFiles(directory=assets_path), name="static-assets")
    else:
        logger.warning(f"Assets directory not found at {assets_path}. /assets path may not work.")

    # You might have other static files in the root of STATIC_FILES_PATH
    # e.g., favicon.ico, manifest.json.
    # For simplicity, we'll let the SPA fallback handle them if they are not critical
    # or add specific routes if needed. Example for favicon:
    # favicon_path = os.path.join(STATIC_FILES_PATH, "favicon.ico")
    # if os.path.exists(favicon_path):
    #     @app.get("/favicon.ico", include_in_schema=False)
    #     async def favicon():
    #         return FileResponse(favicon_path)

    # SPA Fallback: Serve index.html for any other path not caught by API routes or specific static mounts
    logger.info(f"Looking for SPA index at {index_file_path}")
    if os.path.exists(index_file_path):
        logger.info("SPA fallback enabled for non-API, non-static-asset routes.")
        @app.get("/{full_path:path}", include_in_schema=False)
        async def spa_fallback(full_path: str) -> FileResponse:
            """Serve the React SPA entry point for unknown paths."""
            return FileResponse(index_file_path)
    else:
        logger.warning(f"index.html not found at {index_file_path}; SPA fallback will be disabled.")
else:
    # Optional: Log a warning if not in a test environment and static files are not served.
    if not os.getenv("PYTEST_CURRENT_TEST"):
        logger.warning(f"Static files directory '{STATIC_FILES_PATH}' not found. Frontend will not be served by FastAPI.")
